from mantrap.modules.baselines.goal_sum import GoalSumModule
from mantrap.modules.baselines.acc_interact import InteractionAccelerationModule
from mantrap.modules.baselines.pos_interact import InteractionPositionModule

from mantrap.modules.baselines.min_distance import MinDistanceModule
